### ISSUE TITLE
publish on PyPi - wie mache ich das?

### ISSUE THREAD

**Issue by JoeGithub53** [henrydatei/wikifolio-trading-api#1]
habe versucht das wikifolio-trading-api zu testen. Beim PS D:\#flask_TopRoboFolio_ProjektV3> pip install wikifolioTradingAPI
ERROR: Could not find a version that satisfies the requirement wikifolioTradingAPI (from versions: none)
ERROR: No matching distribution found for wikifolioTradingAPI Ich vermute, daß ich den publish on PyPi erst durchführen muesste. Wenn es so ist, kannst Du mir die Schritte beschreiben?

**Comment by henrydatei** [comment]
Ja, das habe ich noch nicht auf PyPi veröffentlicht, deswegen kann er das da nicht finden. Um das Projekt trotzdem zum laufen zu bekommen, clonst du das Repo und in dem Repo kannst du dann einfach eine Datei mit z.B.
```python
from wikifolioTradingAPI import WikifolioTradingAPI

wf_api = WikifolioTradingAPI("my_client_api_key", "my_user_api_key")
print(wf_api.list_wikifolios())
print(wf_api.get_wikifolio('wf0spc2022'))
# print(wf_api.list_wikifolio_underlyings('wf0spc2022')) # Was not working when I tested it
print(wf_api.list_wikifolio_orders('wf0spc2022'))
```
erstellen und ausführen. Also eigentlich genau so wie in meiner unoffiziellen Wikifolio-API.

Ich muss an diesem Projekt mal ein bisschen weiter schreiben und das fertig machen für die Veröffentlichung auf PyPi

**Comment by JoeGithub53** [comment]
Nachdem ich das Rep geclont habe, kommt nach wie vor der Fehler:   from wikifolioTradingAPI import WikifolioTradingAPI
ModuleNotFoundError: No module named 'wikifolioTradingAPI'

**Comment by henrydatei** [comment]
Hm, also bei mir funktioniert es.
- `git clone https://github.com/henrydatei/wikifolio-trading-api`
- `cd wikifolio-trading-api`
- Datei `test.py` anlegen mit dem obigen Inhalt
- `python3 test.py`

So sieht mein Verzeichnis aus:
```
henryhaustein@edr20185 wikifolio-trading-api % ls -l
total 32
-rw-r--r--  1 henryhaustein  staff  1067 24 Jul 15:32 LICENSE
-rw-r--r--  1 henryhaustein  staff  1653 24 Jul 15:32 README.md
drwxr-xr-x  9 henryhaustein  staff   288 24 Jul 15:33 classes
-rw-r--r--  1 henryhaustein  staff   371 24 Jul 15:32 setup.py
-rw-r--r--  1 henryhaustein  staff   246 24 Jul 15:33 test.py
drwxr-xr-x  5 henryhaustein  staff   160 24 Jul 15:33 wikifolioTradingAPI
```

**Comment by JoeGithub53** [comment]
git clone https://github.com/henrydatei/wikifolio-trading-api
git : Die Benennung "git" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms 
erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.   
In Zeile:1 Zeichen:1
+ git clone https://github.com/henrydatei/wikifolio-trading-api
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException   klappt bei mir nicht. Aber ich habe die Dateien per Download in mein Verzeichnis kopiert. Dieses sieht wie folgt aus: "D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\classes"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\#wikifolio_details_mitkey.py"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\__init__.py"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\gitignore.txt"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\LICENSE.txt"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\README.md"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\setup.py"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\wikifolio.py"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\wikifolio_details_mitkey.py"

**Comment by henrydatei** [comment]
Ah, du hast git nicht installiert. Kann man hier machen: https://git-scm.com/downloads

Wenn du das Repo schon heruntergeladen hast, dann kannst du in `D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI` eine Datei mit dem Namen `test.py` anlegen, den Inhalt einfügen, etc.

**Comment by JoeGithub53** [comment]
Mir fehlt die Datei: wikifolioTradingAPI wie komme ich an die ran?

**Comment by JoeGithub53** [comment]
Ach ja, sehe dass es ein Verzeichnis ist. Habe es anglegt und bekomme nun folgende Fehler:  Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\J-KBe\.vscode\extensions\ms-python.debugpy-2024.8.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher\__main__.py", line 91, in <module>
    main()
  File "c:\Users\J-KBe\.vscode\extensions\ms-python.debugpy-2024.8.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher\__main__.py", line 47, in main
    launcher.connect(host, port)
  File "c:\Users\J-KBe\.vscode\extensions\ms-python.debugpy-2024.8.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\launcher\__init__.py", line 27, in connect
    sock.connect((host, port))
ConnectionRefusedError: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte

**Comment by JoeGithub53** [comment]
sieht nach einem Firwall Problem aus. Hast Du einen bestimmten Port freischalten lassen?

**Comment by JoeGithub53** [comment]
Es hat nun geklappt, nachdem ich alle Dateien vom übergeordneten wikifolioTradingAPI ins untergeordnete wikifolioTradingAPI kopiert habe.    Nun passt mein Client Key noch nicht, weil mir die linke Hälfte nicht geschickt wurde. Danke HenryDatei für Deine ausgezeichnete Hilfe!                                                                    "D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\wikifolioTradingAPI\wikifolio.py"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\wikifolioTradingAPI\__pycache__"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\wikifolioTradingAPI\__init__.py"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\wikifolioTradingAPI\gitignore.txt"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\wikifolioTradingAPI\LICENSE.txt"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\wikifolioTradingAPI\README.md"
"D:\#flask_TopRoboFolio_ProjektV3\wikifolioTradingAPI\wikifolioTradingAPI\setup.py"
